[project]
name = "seeker"
version = "0.1.0"
description = "Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "webtypy>=0.1.7"
]

py_modules = [
    "requests",
    "packaging",
    "psutil",
]

[dependency-groups]
dev = [
    "workers-py",
    "workers-runtime-sdk"
]
