[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "seeker"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "webtypy>=0.1.7",
    "requests",
    "packaging",
    "psutil",
]

[tool.setuptools]
py-modules = ["seeker"]
